# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hello-nbdev',
                'doc_host': 'https://proppy.github.io',
                'git_url': 'https://github.com/proppy/hello-nbdev',
                'lib_path': 'hello_nbdev'},
  'syms': {'hello_nbdev.core': {'hello_nbdev.core.foo': ('core.html#foo', 'hello_nbdev/core.py')}}}
